In [2]:
string = 'ab'
print string

ab


In [38]:
import re

a = u'i"m live in Steet No. 55 beijing China我.'
print a

m = re.findall(r'[\u4e00-\u9fa5]', a)

if m:
    print 'm :',m
else:
    print 'no'

res = '[\u4e00-\u9fa5]'

nc = ''
for c in a:
    if c < 20 or c > 'z':
        c = ' '
    nc += c
    
print "nc: ",nc
    

i"m live in Steet No. 55 beijing China我.
m : [u'i', u'm', u'l', u'i', u'e', u'i', u'n', u'S', u't', u'e', u'e', u't', u'N', u'o', u'5', u'5', u'b', u'e', u'i', u'j', u'i', u'n', u'g', u'C', u'h', u'i', u'n', u'a']
nc:  i"m live in Steet No. 55 beijing China .


In [37]:
data = a

english_only

u'i"m live in Steet No. 55 beijing China.'

True

In [56]:
a = 'o(∩∩)o...哈哈'
import codecs

if isinstance(a, unicode):
    print a
    print 'yes'
else:
    print a
    b = unicode(a, 'utf8')
    print b
    print 'what'

o(∩∩)o...哈哈
o(∩∩)o...哈哈
what


In [2]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
alpha,hidden_dim,dropout_percent,do_dropout = (0.5,4,0.2,True)
synapse_0 = 2*np.random.random((3,hidden_dim)) - 1
synapse_1 = 2*np.random.random((hidden_dim,1)) - 1
for j in xrange(60000):
    layer_1 = (1/(1+np.exp(-(np.dot(X,synapse_0)))))
    if(do_dropout):
        layer_1 *= np.random.binomial([np.ones((len(X),hidden_dim))],1-dropout_percent)[0] * (1.0/(1-dropout_percent))
    layer_2 = 1/(1+np.exp(-(np.dot(layer_1,synapse_1))))
    layer_2_delta = (layer_2 - y)*(layer_2*(1-layer_2))
    layer_1_delta = layer_2_delta.dot(synapse_1.T) * (layer_1 * (1-layer_1))
    synapse_1 -= (alpha * layer_1.T.dot(layer_2_delta))
    synapse_0 -= (alpha * X.T.dot(layer_1_delta))
print alpha
print layer_1_delta
print layer_2_delta

0.5
[[  3.09412577e-18   5.88046544e-18   1.76445623e-27  -0.00000000e+00]
 [  3.03865369e-37  -5.80505465e-03   7.15447640e-03   6.60998396e-37]
 [ -1.07597574e-02   1.57767634e-38   2.52027400e-02  -1.07458889e-02]
 [  9.52850476e-09   1.90403257e-08  -3.49647627e-08   9.38394853e-09]]
[[  1.75613328e-18]
 [ -1.73361272e-03]
 [ -6.10691659e-03]
 [  8.47236804e-09]]


In [3]:
import theano