In [9]:
import numpy as np
npa = np.arange(25)
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
npa.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
npa.shape

(25,)

In [13]:
np.zeros((5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
npa2 = np.zeros((5,5))

In [16]:
npa2.shape

(5, 5)

In [17]:
npa2.ndim

2

In [20]:
np.arange(8).reshape(2,2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
np.zeros((4,4,4,4))

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.

In [24]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [26]:
npa2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [28]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
np.random.seed(10)
np.random.random_integers(1,10, 25)

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [34]:
np.random.seed(10)
npa2 = np.random.random_integers(1,10,25).reshape(5,5)
npa2

array([[10,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [36]:
npa3 = np.random.random_integers(1,10,25).reshape(5,5)
npa3

array([[ 5,  8,  9,  9,  3],
       [ 7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1],
       [ 7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10]])

In [37]:
npa2 > npa3

array([[ True, False, False, False,  True],
       [False, False, False,  True, False],
       [ True,  True, False,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False]], dtype=bool)

In [38]:
(npa2 > npa3).sum()

8

In [40]:
(npa2 > npa3).sum(axis = 0 )

array([3, 1, 1, 2, 1])

In [41]:
npa2.max(axis=0)

array([10,  7,  9, 10, 10])

In [42]:
npa2.transpose()

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [43]:
npa2.T

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [44]:
npa2.T * npa2

array([[100,   5,   9,  10,  50],
       [  5,   4,  63,  70,   2],
       [  9,  63,  25,  36,   4],
       [ 10,  70,  36,   4,  63],
       [ 50,   2,   4,  63,  36]])

In [45]:
npa2 * npa2.T

array([[100,   5,   9,  10,  50],
       [  5,   4,  63,  70,   2],
       [  9,  63,  25,  36,   4],
       [ 10,  70,  36,   4,  63],
       [ 50,   2,   4,  63,  36]])

In [46]:
npa2.flatten()

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [47]:
r = npa2.ravel()

In [48]:
r

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [49]:
npa2.flatten()[0] = 25

In [50]:
npa2

array([[10,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [51]:
r[0] = 25

In [52]:
r

array([25,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [53]:
npa2.flatten()[1] = 25

In [54]:
npa2

array([[25,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [55]:
npa2.flatten()[2] = 25

In [56]:
npa2

array([[25,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [57]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
npa.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300])

In [59]:
npa.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [61]:
ndim_ar = np.arange(12).reshape(3,4)
ndim_ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
ndiam_ar2 = np.random.random_integers(12, size=(3,4))
ndiam_ar2

array([[ 3,  6, 10,  1],
       [11,  2,  1,  2],
       [10,  1, 10, 11]])

In [65]:
ndiam_ar3 = np.arange(8).reshape(2,2,2)
ndiam_ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
ar  = np.arange(11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
ar[1:6:2]

array([1, 3, 5])

In [71]:
ndim_ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
ndim_ar[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [74]:
ndim_ar[1:3, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
ndiam_ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
ar2 = np.random.random_integers(0, 10, 11)
ar2

array([ 0,  2,  3,  3,  2,  6, 10,  0,  5,  1,  3])

In [82]:
np.vstack((ar,ar2))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  2,  3,  3,  2,  6, 10,  0,  5,  1,  3]])

In [83]:
np.hstack((ar,ar2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  2,  3,  3,  2,  6,
       10,  0,  5,  1,  3])

In [84]:
np.concatenate((ar,ar2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  2,  3,  3,  2,  6,
       10,  0,  5,  1,  3])

In [85]:
np.concatenate((ndim_ar, ndiam_ar2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 3,  6, 10,  1],
       [11,  2,  1,  2],
       [10,  1, 10, 11]])

In [86]:
np.concatenate((ndim_ar, ndiam_ar2), axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 3,  6, 10,  1],
       [11,  2,  1,  2],
       [10,  1, 10, 11]])

In [87]:
np.concatenate((ndim_ar, ndiam_ar2), axis = 1)

array([[ 0,  1,  2,  3,  3,  6, 10,  1],
       [ 4,  5,  6,  7, 11,  2,  1,  2],
       [ 8,  9, 10, 11, 10,  1, 10, 11]])

In [88]:
ndiam_ar3d_stack = np.dstack((ndim_ar, ndiam_ar2))

In [89]:
ndiam_ar3d_stack

array([[[ 0,  3],
        [ 1,  6],
        [ 2, 10],
        [ 3,  1]],

       [[ 4, 11],
        [ 5,  2],
        [ 6,  1],
        [ 7,  2]],

       [[ 8, 10],
        [ 9,  1],
        [10, 10],
        [11, 11]]])

In [94]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
np.hsplit(ar, 2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [96]:
ndiam_ar2

array([[ 3,  6, 10,  1],
       [11,  2,  1,  2],
       [10,  1, 10, 11]])

In [102]:
np.vsplit(np.concatenate((ndiam_ar2, ndiam_ar2)), 2)

[array([[ 3,  6, 10,  1],
        [11,  2,  1,  2],
        [10,  1, 10, 11]]), array([[ 3,  6, 10,  1],
        [11,  2,  1,  2],
        [10,  1, 10, 11]])]

In [98]:
np.hsplit(ndiam_ar2, 2)

[array([[ 3,  6],
        [11,  2],
        [10,  1]]), array([[10,  1],
        [ 1,  2],
        [10, 11]])]