In [4]:
import numpy as np
npa = np.arange(25)
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
npa.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
npa.shape

(25,)

In [7]:
np.zeros((5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
npa2 = np.zeros((5,5))

In [9]:
npa2.shape

(5, 5)

In [10]:
npa2.ndim

2

In [11]:
np.arange(8).reshape(2,2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
np.zeros((4,4,4,4))

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.

In [13]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [14]:
npa2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
np.random.seed(10)
np.random.random_integers(1,10, 25)

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [17]:
np.random.seed(10)
npa2 = np.random.random_integers(1,10,25).reshape(5,5)
npa2

array([[10,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [18]:
npa3 = np.random.random_integers(1,10,25).reshape(5,5)
npa3

array([[ 4, 10,  7, 10,  2],
       [10,  5,  3,  7,  8],
       [ 9,  9, 10,  3,  1],
       [ 7,  8,  9,  2,  8],
       [ 2,  5,  1,  9,  6]])

In [19]:
npa2 > npa3

array([[ True, False, False, False,  True],
       [False, False,  True,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [ True, False,  True, False, False]], dtype=bool)

In [20]:
(npa2 > npa3).sum()

8

In [21]:
(npa2 > npa3).sum(axis = 0 )

array([2, 0, 2, 2, 2])

In [22]:
npa2.max(axis=0)

array([10,  7,  9, 10, 10])

In [23]:
npa2.transpose()

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [24]:
npa2.T

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [25]:
npa2.T * npa2

array([[100,   5,   9,  10,  50],
       [  5,   4,  63,  70,   2],
       [  9,  63,  25,  36,   4],
       [ 10,  70,  36,   4,  63],
       [ 50,   2,   4,  63,  36]])

In [26]:
npa2 * npa2.T

array([[100,   5,   9,  10,  50],
       [  5,   4,  63,  70,   2],
       [  9,  63,  25,  36,   4],
       [ 10,  70,  36,   4,  63],
       [ 50,   2,   4,  63,  36]])

In [27]:
npa2.flatten()

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [28]:
r = npa2.ravel()

In [29]:
r

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [30]:
npa2.flatten()[0] = 25

In [31]:
npa2

array([[10,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [32]:
r[0] = 25

In [33]:
r

array([25,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])

In [34]:
npa2.flatten()[1] = 25

In [35]:
npa2

array([[25,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [36]:
npa2.flatten()[2] = 25

In [37]:
npa2

array([[25,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [38]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
npa.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300])

In [40]:
npa.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [41]:
ndim_ar = np.arange(12).reshape(3,4)
ndim_ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
ndiam_ar2 = np.random.random_integers(12, size=(3,4))
ndiam_ar2

array([[5, 8, 9, 9],
       [3, 7, 3, 9],
       [9, 7, 7, 6]])

In [43]:
ndiam_ar3 = np.arange(8).reshape(2,2,2)
ndiam_ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
ar  = np.arange(11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
ar[1:6:2]

array([1, 3, 5])

In [47]:
ndim_ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
ndim_ar[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [49]:
ndim_ar[1:3, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
ndiam_ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
ar2 = np.random.random_integers(0, 10, 11)
ar2

array([10,  6,  0,  0,  6,  9,  1,  8, 10,  9,  1])

In [53]:
np.vstack((ar,ar2))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10,  6,  0,  0,  6,  9,  1,  8, 10,  9,  1]])

In [54]:
np.hstack((ar,ar2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10,  6,  0,  0,  6,  9,
        1,  8, 10,  9,  1])

In [55]:
np.concatenate((ar,ar2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10,  6,  0,  0,  6,  9,
        1,  8, 10,  9,  1])

In [56]:
np.concatenate((ndim_ar, ndiam_ar2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 5,  8,  9,  9],
       [ 3,  7,  3,  9],
       [ 9,  7,  7,  6]])

In [57]:
np.concatenate((ndim_ar, ndiam_ar2), axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 5,  8,  9,  9],
       [ 3,  7,  3,  9],
       [ 9,  7,  7,  6]])

In [58]:
np.concatenate((ndim_ar, ndiam_ar2), axis = 1)

array([[ 0,  1,  2,  3,  5,  8,  9,  9],
       [ 4,  5,  6,  7,  3,  7,  3,  9],
       [ 8,  9, 10, 11,  9,  7,  7,  6]])

In [59]:
ndiam_ar3d_stack = np.dstack((ndim_ar, ndiam_ar2))

In [60]:
ndiam_ar3d_stack

array([[[ 0,  5],
        [ 1,  8],
        [ 2,  9],
        [ 3,  9]],

       [[ 4,  3],
        [ 5,  7],
        [ 6,  3],
        [ 7,  9]],

       [[ 8,  9],
        [ 9,  7],
        [10,  7],
        [11,  6]]])

In [61]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
np.hsplit(ar, 2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [63]:
ndiam_ar2

array([[5, 8, 9, 9],
       [3, 7, 3, 9],
       [9, 7, 7, 6]])

In [64]:
np.vsplit(np.concatenate((ndiam_ar2, ndiam_ar2)), 2)

[array([[5, 8, 9, 9],
        [3, 7, 3, 9],
        [9, 7, 7, 6]]), array([[5, 8, 9, 9],
        [3, 7, 3, 9],
        [9, 7, 7, 6]])]

In [65]:
np.hsplit(ndiam_ar2, 2)

[array([[5, 8],
        [3, 7],
        [9, 7]]), array([[9, 9],
        [3, 9],
        [7, 6]])]

In [88]:
from numpy import matrix
A = matrix('1.0 2.0; 3.0 4.0')
print(type(A))
A


<class 'numpy.matrixlib.defmatrix.matrix'>


matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [81]:
alist =  A.tolist()
alist

[[1.0, 2.0], [3.0, 4.0]]

In [83]:
print type(alist)
alist[0]

<type 'list'>


[1.0, 2.0]

In [78]:
blist = np.array(alist)
blist

array(<bound method matrix.tolist of matrix([[ 1.,  2.],
        [ 3.,  4.]])>, dtype=object)

<read-write buffer for 0x2c03930, size 8, offset 0 at 0x7f0e4c1174f0>

In [85]:
a = u'\u65f6\u5de6\u53f3,\u7f57\u6e56\u533a\u5ef6\u82b3\u8def\u6c61\u6c34'
print a

时左右,罗湖区延芳路污水


In [86]:
b = u'"title":"\u4e91\u5357\u4e34\u6ca7\u53e3\u5cb8\u4fbf\u5229\u5316\u901a\u5173\u52a9\u63a8\u8fb9\u5883\u519c\u4e1a<\/em>\u53d1\u5c55\u63d0\u901f", "abstract":"\u592e\u5e7f\u7f51\u4e34\u6ca72\u67081\u65e5\u6d88\u606f(\u8bb0\u8005\u674e\u5065\u98de \u901a\u8baf\u5458\u5f20\u4fca)\u968f\u7740\u56fd\u5bb6\u201c\u4e00\u5e26\u4e00\u8def\u201d\u6218\u7565\u7684\u63a8\u8fdb,\u4f4d\u4e8e\u4e2d\u7f05\u8fb9\u5883\u7684\u4e91\u5357\u4e34\u6ca7\u5e02\u8fb9\u5883\u519c\u4e1a<\/em>\u53d1\u5c55\u65b0\u673a\u9047,\u519c\u4ea7\u54c1\u3001\u5927\u5b97\u5546\u54c1\u8fdb\u51fa\u53e3\u7ecf\u8d38\u6301\u7eed\u5347\u6e29,...", "code":" ", "timeShow":"2016-2-1", "lastModified":"2016-2-1", '
print b

"title":"云南临沧口岸便利化通关助推边境农业<\/em>发展提速", "abstract":"央广网临沧2月1日消息(记者李健飞 通讯员张俊)随着国家“一带一路”战略的推进,位于中缅边境的云南临沧市边境农业<\/em>发展新机遇,农产品、大宗商品进出口经贸持续升温,...", "code":" ", "timeShow":"2016-2-1", "lastModified":"2016-2-1", 


In [92]:
from scipy import sparse
ap = np.array([[1,0,1],[0,0,1]])
bp = sparse.csr_matrix(ap)
print bp
print type(bp)

  (0, 0)	1
  (0, 2)	1
  (1, 2)	1
<class 'scipy.sparse.csr.csr_matrix'>
