In [47]:
import numpy as np
import pandas as pd


In [48]:
np.random.seed(20)
X = np.random.random_integers(1, 50, 25)
X = X.reshape(len(X),1)
X

array([[36],
       [27],
       [16],
       [32],
       [29],
       [27],
       [10],
       [21],
       [12],
       [23],
       [ 8],
       [35],
       [33],
       [41],
       [22],
       [27],
       [27],
       [20],
       [17],
       [39],
       [39],
       [17],
       [42],
       [38],
       [ 8]])

In [49]:
def foo(x):
    return 0.4 * x * x + 0.3 * x + 0.1

y = [  foo(r)  for r in X]
y = np.array(y)
y = y.reshape(len(y), 1)
y

array([[ 529.3],
       [ 299.8],
       [ 107.3],
       [ 419.3],
       [ 345.2],
       [ 299.8],
       [  43.1],
       [ 182.8],
       [  61.3],
       [ 218.6],
       [  28.1],
       [ 500.6],
       [ 445.6],
       [ 684.8],
       [ 200.3],
       [ 299.8],
       [ 299.8],
       [ 166.1],
       [ 120.8],
       [ 620.2],
       [ 620.2],
       [ 120.8],
       [ 718.3],
       [ 589.1],
       [  28.1]])

In [57]:

print X.shape, y.shape

(25, 1) (25, 1)


In [58]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X, y)
lr.predict([1])

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[-187.49656424]])

In [63]:
from sklearn.svm import LinearSVR
svc = LinearSVR()
svc.fit(X, y)
svc.predict([1])

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 5.99892683])

In [64]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(X, y)
svr.predict([1])

/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:216: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True).astype(np.float64)
/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 298.68168447])